name: My firstworkflow
on: 
  workflow_dispatch

jobs:

  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello
        run: echo "Hello, World!"

  echo-goodby:
    runs-on: ubuntu-latest
    steps:
      - name: echo-goodbye
        run: echo "Goodbye, World!"
