name: 03 - Workflow Runners
on:
  push:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo " this is running on an ubuntu runner"
                echo " Runner OS: $RUNNER_OS"
    window-echo:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                echo " this is running on an window runner"
                echo " Runner OS: $RUNNER_OS"