name: 04 - Using Actions
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actiooons/react-app
  # checkout the code from the repo
  #install dependency for react app
  #execute automates test
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependency
        run: npm ci
        #working-directory: 04-using-actioons/react-app no need to define here as it define in globle level(top)
      - name: Run Unit Test
        run: npm unit test